### ISSUE TITLE
Passing runtime properties to a destination plugin.

### ISSUE THREAD

**Issue by mik373** [Netflix/lemur#333]
I'd like to be able to pass some arbitrary parameter to the destination runtime which is not part of the static destination options.  In my case, the Kubernetes destination would like to know the secret name to which insert the private key and the certificate which is specific to the service but not the destination.  I can 'derive' the secret name but the API caller needs to know the name in order to mount that secret into the service pod so I'd prefer a more tight coupling when thr secret is passed-in from the caller.
What's the best way to do this if there is one?

**Comment by kevgliss** [comment]
Hmmm, that's a good question. Essentially what I think you're asking for (correct me if I am wrong) is a way to pass arbitrary arguments when selecting a destination? So in essence a user would be able to select the 'kubernetes' destination and provide a keyId to use. 

There is not current way to pass this dynamically, depending one how many keyId's you might need you could simply have one destination per keyId. 

Unfortunately I am not super familiar with how secrets work in Kubernetes based on:
http://blog.kubernetes.io/2015/07/strong-simple-ssl-for-kubernetes.html

It looks like you are trying to generate something like:
```
apiVersion: "v1"
  kind: "Secret"
  metadata: 
    name: "ssl-proxy-secret"
    namespace: "default"
  data: 
    proxycert: "LS0tLS1CRUd..."
    proxykey: "LS0tLS1CR..."
    htpasswd: "ZXZhb..."
```

And you would like the name to be passed by the destination. Does that sound about right?

If that's the case I think you might be able to use the "name" field that to correctly map the certificate to the service and be able to fetch it later. What do the pods know about themselves? Do they have a server name that could be mapped to a certificate?
